server:
  port: 8080

spring:
  application:
    name: student-service

  datasource:
    url: jdbc:mysql://localhost:3306/university
    username: root
    password: root

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true